/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusDadosRouteImport } from './routes/meus-dados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminPremiosRouteImport } from './routes/admin.premios'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminPostosRouteImport } from './routes/admin.postos'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const MeusDadosRoute = MeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiosRoute = AdminPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostosRoute = AdminPostosRouteImport.update({
  id: '/postos',
  path: '/postos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/postos': typeof AdminPostosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/premios': typeof AdminPremiosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/postos': typeof AdminPostosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/premios': typeof AdminPremiosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/postos': typeof AdminPostosRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/premios': typeof AdminPremiosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/meus-dados'
    | '/admin/banners'
    | '/admin/postos'
    | '/admin/precos'
    | '/admin/premios'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/meus-dados'
    | '/admin/banners'
    | '/admin/postos'
    | '/admin/precos'
    | '/admin/premios'
    | '/admin/servicos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/meus-dados'
    | '/admin/banners'
    | '/admin/postos'
    | '/admin/precos'
    | '/admin/premios'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeusDadosRoute: typeof MeusDadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-dados': {
      id: '/meus-dados'
      path: '/meus-dados'
      fullPath: '/meus-dados'
      preLoaderRoute: typeof MeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premios': {
      id: '/admin/premios'
      path: '/premios'
      fullPath: '/admin/premios'
      preLoaderRoute: typeof AdminPremiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/postos': {
      id: '/admin/postos'
      path: '/postos'
      fullPath: '/admin/postos'
      preLoaderRoute: typeof AdminPostosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminPostosRoute: typeof AdminPostosRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminPremiosRoute: typeof AdminPremiosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminPostosRoute: AdminPostosRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminPremiosRoute: AdminPremiosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MeusDadosRoute: MeusDadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
