/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as MeusDadosRouteImport } from './routes/meus-dados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AtualizarSenhaRouteImport } from './routes/atualizar-senha'
import { Route as IndexRouteImport } from './routes/index'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDadosRoute = MeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarSenhaRoute = AtualizarSenhaRouteImport.update({
  id: '/atualizar-senha',
  path: '/atualizar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/login': typeof LoginRoute
  '/meus-dados': typeof MeusDadosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizar-senha'
    | '/login'
    | '/meus-dados'
    | '/recuperar-senha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atualizar-senha' | '/login' | '/meus-dados' | '/recuperar-senha'
  id:
    | '__root__'
    | '/'
    | '/atualizar-senha'
    | '/login'
    | '/meus-dados'
    | '/recuperar-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtualizarSenhaRoute: typeof AtualizarSenhaRoute
  LoginRoute: typeof LoginRoute
  MeusDadosRoute: typeof MeusDadosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-dados': {
      id: '/meus-dados'
      path: '/meus-dados'
      fullPath: '/meus-dados'
      preLoaderRoute: typeof MeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-senha': {
      id: '/atualizar-senha'
      path: '/atualizar-senha'
      fullPath: '/atualizar-senha'
      preLoaderRoute: typeof AtualizarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtualizarSenhaRoute: AtualizarSenhaRoute,
  LoginRoute: LoginRoute,
  MeusDadosRoute: MeusDadosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
